"""
Input Writer: Config Model Factory: Pydantic Config Model Factory.

Dynamically creates Pydantic models from Input Writer: Schema Scraper schemas.
Runtime service that loads pre-generated JSON schemas and validates inputs.

Architecture:
- Loads schemas from database/schemas/ (generated by Input Writer: Schema Scraper)
- Uses pydantic.create_model for dynamic model generation
- Integrates with Metadata Schema parse_inputs() for text parsing
- Supports Load-Modify-Write pattern (Amendment C)
- Filters parameters by build config (Amendment D)

References
----------
- Input Writer: Schema Scraper: SchemaBuilder (database/scripts/build_schema.py)
- Metadata Schema: BaseAMReXConfig.parse_inputs()
- PRD Amendment C: Load-Modify-Write requirement
- PRD Amendment D: Build-conditional parameters
"""

import json
import logging
import re
from pathlib import Path
from typing import Any, TypedDict, Union

from pydantic import BaseModel, ConfigDict, Field, create_model


class ParameterMapping(BaseModel):
    """Single parameter mapping from semantic name to schema field."""

    from_param: str = Field(alias='from')
    to: str | None = None
    transform: str | None = None
    formatted_value: str | None = None

class MappingExtraction(BaseModel):
    """Extracted mappings from LLM."""

    mappings: list[ParameterMapping]

class RemapResult(TypedDict):
    """Structured remap details for diagnostics and feedback."""

    from_param: str
    to_param: str
    transform: str | None
    formatted_value: Any | None
    values: list[Any]
    reason: str | None

logger = logging.getLogger(__name__)

class ConfigModelFactory:
    """Factory for creating dynamic Pydantic models from AMReX schemas."""

    @staticmethod
    def load_schema(schema_path: Path) -> dict[str, Any]:
        """
        Load schema from JSON file, handling both nested and flat formats.

        Handles two schema formats:
        1. Nested format (from build_schema.py v2):
           {
             "metadata": {...},
             "parameters": {
               "param.name": {...},
               ...
             }
           }

        2. Flat format (legacy):
           {
             "param.name": {...},
             ...
           }

        Always returns the flat parameters dictionary.

        Parameters
        ----------
        schema_path : Path
            Path to schema JSON (from Input Writer: Schema Scraper).

        Returns
        -------
        dict
            Flat schema dictionary: {"param.name": {...}, ...}.
        """
        with open(schema_path) as f:
            schema_data = json.load(f)

        # Handle nested format (preferred)
        if isinstance(schema_data, dict) and 'parameters' in schema_data:
            schema = schema_data.get('parameters', {})
            logger.debug(
                f"Loaded nested schema with {len(schema)} parameters "
                f"from {schema_path.name}"
            )
            return schema

        # Handle flat format (legacy)
        logger.debug(
            f"Loaded flat schema with {len(schema_data)} entries "
            f"from {schema_path.name}"
        )
        return schema_data


    @staticmethod
    def _check_dependencies(
        dependencies: list[str],
        build_config: dict[str, str]
    ) -> bool:
        """
        Check if all dependencies are satisfied in build config.

        Supports:
        - Simple flags: "USE_EB"
        - Negation: "!USE_EB"
        - Equality: "DIM==3"

        Args:
            dependencies: List of dependency expressions
            build_config: Build configuration (e.g., {"USE_EB": "TRUE"})

        Returns
        -------
            True if all dependencies satisfied
        """
        if not dependencies:
            return True

        for dep in dependencies:
            # 1. Handle Negation (!FLAG)
            if dep.startswith('!'):
                flag = dep[1:]
                val = build_config.get(flag, 'FALSE').upper()
                if val in ['TRUE', 'ON', '1', 'YES']:
                    return False

            # 2. Handle Equality (VAR==VAL)
            elif '==' in dep:
                var, val = dep.split('==')
                if build_config.get(var.strip()) != val.strip():
                    return False

            # 3. Handle Simple Flag (FLAG)
            else:
                val = build_config.get(dep, 'FALSE').upper()
                if val not in ['TRUE', 'ON', '1', 'YES']:
                    return False

        return True

    @staticmethod
    def _is_cpp_expression(value) -> bool:
        """Check if a value looks like a C++ code expression that shouldn't be used as a default."""
        if not isinstance(value, str):
            return False

        cpp_markers = [
            'std::', 'amrex::', '::',
            '->', 'max(', 'min(',
            'nullptr', 'isOpen',
            'getVerbose()', 'm_verbose',
            'constants::'
        ]
        return any(marker in value for marker in cpp_markers)

    @staticmethod
    def create_from_schema(
        schema: dict[str, Any],
        build_config: dict[str, str]
    ) -> type[BaseModel]:
        """
        Dynamically create a Pydantic model from Input Writer: Schema Scraper schema.

        Parameters
        ----------
        schema : dict
            Flat schema dictionary from ``load_schema`` or extracted parameters.
        build_config : dict
            Active build flags (e.g., {"USE_EB": "TRUE", "DIM": "3"}).

        Returns
        -------
        Type[BaseModel]
            Dynamically created Pydantic model class.

        Architecture:
            - Uses create_model for runtime schema loading
            - Handles AMReX dot-notation via aliases (amr.n_cell → amr_n_cell)
            - Filters parameters by build dependencies (Amendment D)
            - Permissive mode (extra='allow') per architecture decision
            - Strict type enforcement: numeric Union types have NO str fallback
        """
        # Extract parameters from nested structure if present
        # Handles both nested format {"parameters": {...}} and flat format
        if isinstance(schema, dict) and "parameters" in schema:
            # Nested format: {"metadata": {...}, "parameters": {"param.name": {...}}}
            params = schema.get("parameters", {})
            logger.debug(
                f"Extracting parameters from nested schema: {len(params)} params found"
            )
        else:
            # Flat format or already extracted: {"param.name": {...}, ...}
            params = schema
            logger.debug(
                f"Using flat schema: {len(params)} params found"
            )

        fields = {}

        for param_name, details in params.items():
            # Amendment D: Build flag/dependency filtering
            # Use _check_dependencies for both (it's more robust)

            # Check build_flags (simple list of required flags)
            build_flags = details.get('build_flags', [])
            if build_flags and build_config and not ConfigModelFactory._check_dependencies(build_flags, build_config):
                continue  # Exclude - required build flag not enabled

            # Check dependencies (complex dependency expressions)
            dependencies = details.get("dependencies", [])
            if dependencies and build_config and not ConfigModelFactory._check_dependencies(dependencies, build_config):
                continue  # Exclude - dependency not satisfied

            # Map C++ types to Python types
            cpp_type = details.get("type", "str")
            is_array = details.get("is_array", False)
            py_type = ConfigModelFactory._map_type(cpp_type, is_array)

            # Handle required vs optional
            is_required = details.get("required", False)
            default_value = details.get("default")

            # Amendment C: ALL fields are Optional in Pydantic
            # Schema 'required' is metadata for Rule Engine, NOT Pydantic validation
            # This allows sparse configs (Load-Modify-Write pattern)

            # Build field description with AMReX metadata for runtime access
            base_desc = (
                f"Type: {cpp_type}, "
                f"Array: {is_array}, "
                f"Required: {is_required}, "
                f"Source: {details.get('source_file', 'unknown')}"
            )
            doc = details.get("description")
            description = f"{base_desc}, Doc: {doc}" if doc else base_desc

            if default_value is not None and ConfigModelFactory._is_cpp_expression(default_value):
                logger.debug(
                    f"Skipping C++ expression default for {param_name}: {default_value}"
                )
                default_value = None  # Treat as if no default was provided

            if default_value is not None:
                # Has explicit default value - coerce it to proper type
                try:
                    # Create a temporary FieldInfo for coercion
                    # This allows _coerce_amrex_value to access the is_array metadata
                    temp_field = Field(
                        default=None,
                        description=description
                    )

                    # Coerce default using AMReX-aware logic
                    # This respects is_array and other schema metadata
                    coerced_default = ConfigModelFactory._coerce_amrex_value(
                        str(default_value),  # Convert to string for coercion
                        py_type,
                        temp_field
                    )

                    logger.debug(
                        f"Coerced default for {param_name}: {default_value!r} "
                        f"({type(default_value).__name__}) → {coerced_default!r} "
                        f"({type(coerced_default).__name__})"
                    )

                    field_def = (
                        py_type | None,
                        Field(
                            default=coerced_default,
                            alias=param_name,
                            alias_priority=2,
                            description=description
                        )
                    )
                except Exception as e:
                    # Coercion failed - fall back to None
                    logger.warning(
                        f"Could not coerce default for {param_name}: {e}, using None instead"
                    )
                    field_def = (
                        py_type | None,
                        Field(
                            default=None,
                            alias=param_name,
                            alias_priority=2,
                            description=description
                        )
                    )
            else:
                # No default value - use None (makes it Optional)
                field_def = (
                    py_type | None,
                    Field(
                        default=None,
                        alias=param_name,
                        alias_priority=2,
                        description=description
                    )
                )

            # Convert param.name to param_name for Python attribute
            safe_name = param_name.replace(".", "_").replace("-", "_")
            fields[safe_name] = field_def

        # Create model with permissive config
        model_class = create_model(
            "AMReXConfig",
            __config__=ConfigDict(
                extra='allow',           # Allow unknown parameters
                populate_by_name=True    # Support both amr_n_cell and amr.n_cell
            ),
            **fields
        )

        return model_class

    @staticmethod
    def hydrate(
        model_class: type[BaseModel],
        inputs_text: str
    ) -> BaseModel:
        """
        Load raw AMReX inputs text into typed Pydantic model.

        Per PRD Amendment C: Object Manipulation (typed storage)
        Per PRD Amendment D: UQ sweeps (numerical operations)

        Reuses Metadata Schema parse_inputs() to avoid duplicating parser logic.
        Applies lenient coercion for flexible AMReX formats.

        Parameters
        ----------
        model_class : Type[BaseModel]
            Pydantic model created by ``create_from_schema``.
        inputs_text : str
            Raw AMReX inputs file content.

        Returns
        -------
        BaseModel
            Hydrated and validated model instance.
        """
        # Reuse Metadata Schema parser
        from database.configs.base_amrex_config import BaseAMReXConfig

        logger.debug("[HYDRATE] Starting baseline hydration with AMReX-aware coercion")

        raw_dict = BaseAMReXConfig.parse_inputs(inputs_text)
        logger.debug(f"[HYDRATE] Parsed {len(raw_dict)} parameters from inputs")

        # Log model structure
        logger.debug(f"[HYDRATE] Model has {len(model_class.model_fields)} fields")

        # ===== AMReX-AWARE COERCION FOR ALL VALUES =====
        # Per Amendment C/D: Handle flexible AMReX formats
        # Uses AMReX ParmParse API semantics via _coerce_amrex_value
        # CRITICAL: Coerce ALL values (strings, ints, floats) with schema metadata
        # This ensures baseline parameters are typed correctly before hydration
        coerced_dict = {}
        coercion_count = 0
        unknown_fields = 0
        none_fields = 0

        for key, value in raw_dict.items():
            # Skip None values
            if value is None:
                coerced_dict[key] = value
                none_fields += 1
                continue

            # Find field name (with dot conversion)
            field_name = key.replace('.', '_').replace('-', '_')

            # Check if field exists in model
            if field_name not in model_class.model_fields:
                # Unknown field - pass through (extra='allow')
                coerced_dict[key] = value
                unknown_fields += 1
                logger.debug(f"[HYDRATE] Unknown field (extra='allow'): {key} = {value!r}")
                continue

            # Get field type and metadata
            field_info = model_class.model_fields[field_name]
            field_type = field_info.annotation

            # ===== UNIFIED COERCION PATH =====
            # Apply AMReX-aware coercion to ALL values, including non-strings
            # This respects schema metadata (is_array, required) for proper typing

            # Convert non-string values back to strings for uniform processing
            # This allows _coerce_amrex_value to apply AMReX metadata correctly
            if isinstance(value, str):
                value_str = value
            elif isinstance(value, (int, float, bool)):
                value_str = str(value)
            elif isinstance(value, list):
                # Multi-part value (e.g., from space-separated parsing)
                value_str = " ".join(str(v) for v in value)
            else:
                # Unknown type - pass through
                coerced_dict[key] = value
                logger.debug(f"[HYDRATE] Skipped non-coercible type: {key} ({type(value).__name__})")
                continue

            # Apply AMReX-aware coercion using schema metadata
            original_type = type(value).__name__
            coerced_value = ConfigModelFactory._coerce_amrex_value(
                value_str, field_type, field_info
            )
            new_type = type(coerced_value).__name__
            coerced_dict[key] = coerced_value

            # Log coercion with type change detection
            if original_type != new_type:
                logger.debug(
                    f"[HYDRATE] Coerced {key}: {value!r} ({original_type}) "
                    f"→ {coerced_value!r} ({new_type})"
                )
                coercion_count += 1
            else:
                logger.debug(
                    f"[HYDRATE] Type unchanged {key}: {value!r} ({original_type})"
                )

        logger.debug(
            f"[HYDRATE] Coercion summary: {coercion_count} type changes, "
            f"{none_fields} None values, {unknown_fields} unknown fields"
        )

        # Verify critical fields that were problematic
        test_fields = [
            'pelec_external_forcing',
            'pelec_domlo_isothermal_temp',
            'amr_blocking_factor',
            'amr_n_cell'
        ]
        logger.debug("[HYDRATE] Verifying critical fields in coerced_dict (before Pydantic):")
        for field in test_fields:
            # Check with dot notation (as keys in coerced_dict)
            dot_key = field.replace('_', '.')
            if dot_key in coerced_dict:
                value = coerced_dict[dot_key]
                logger.debug(
                    f"[HYDRATE]   {dot_key} = {value!r} (type: {type(value).__name__})"
                )

        # Pass dotted keys directly to Pydantic
        # populate_by_name=True allows Pydantic to accept both "amr.n_cell" and "amr_n_cell"
        # By passing dotted keys, model_dump(by_alias=True) will use aliases correctly
        logger.debug(f"[HYDRATE] Creating Pydantic model instance with {len(coerced_dict)} dotted keys...")
        try:
            config = model_class(**coerced_dict)
        except Exception as exc:
            message = (
                "Hydration failed during Pydantic validation. "
                "This usually happens when inputs contain parser expressions "
                "(e.g., '10*nano', 'nx ny nz', '-0.5*Lx') for fields typed as numeric, "
                "or when schema defaults are C++ expressions that cannot be coerced "
                "to plain values. Consider using numeric literals or updating the "
                "schema/type handling to allow parser expressions."
            )
            logger.warning(message)
            raise RuntimeError(message) from exc

        # Final verification after model creation
        logger.debug("[HYDRATE] Final verification after model instantiation:")
        for field in test_fields:
            if hasattr(config, field):
                value = getattr(config, field)
                logger.debug(
                    f"[HYDRATE]   config.{field} = {value!r} (type: {type(value).__name__})"
                )

        logger.debug("[HYDRATE] Complete - baseline hydration successful")
        return config




    @staticmethod
    def serialize_with_dots(config: BaseModel) -> dict[str, Any]:
        """
        Serialize Pydantic model back to dot notation for compatibility with AMReX.

        Pydantic field names use underscores (amr_n_cell) for Python compatibility,
        but AMReX parameters use dot notation (amr.n_cell). This method serializes
        using the field aliases (which are the dot-notation names).

        Parameters
        ----------
        config : BaseModel
            Pydantic BaseModel instance with underscore field names.

        Returns
        -------
        dict
            Dot-notation parameter names (e.g., {"amr.n_cell": [...] }).

        Example:
            >>> config.amr_n_cell = [512, 512]
            >>> serialized = ConfigModelFactory.serialize_with_dots(config)
            >>> serialized["amr.n_cell"]  # Dot notation!
            [512, 512]
        """
        # Get raw values using field names (underscores)
        flat_dict = config.model_dump(exclude_none=True)

        # Map field names back to original parameter names (with dots) using aliases
        dot_dict = {}
        model_class = config.__class__

        for field_name, value in flat_dict.items():
            # Look up the alias (original param name with dots) from model_fields
            field_info = model_class.model_fields.get(field_name)

            if field_info and field_info.alias:
                # Use the stored alias (original dot notation)
                param_name = field_info.alias
                logger.debug(f"Using alias: {field_name} → {param_name}")
            else:
                # Fallback: use field name as-is if no alias
                param_name = field_name
                logger.debug(f"No alias found for {field_name}, using field name")

            dot_dict[param_name] = value

        return dot_dict

    @staticmethod
    def from_dict(
        model_class: type[BaseModel],
        data_dict: dict[str, Any]
    ) -> BaseModel:
        """
        Create model instance directly from dictionary.

        Alternative to hydrate() when data is already parsed.
        Useful when baseline comes from _load_baseline() (dict format).

        Parameters
        ----------
        model_class : Type[BaseModel]
            Pydantic model class to instantiate.
        data_dict : dict
            Dictionary of parameter values in dot or underscore notation.

        Returns
        -------
        BaseModel
            Hydrated model instance.
        """
        # Convert dict values through model validation
        # Pydantic will handle type coercion via field validators
        try:
            return model_class(**data_dict)
        except Exception as e:
            # If direct instantiation fails, it might be due to
            # string values that need parsing
            # Try converting to text and using hydrate()
            import logging
            logger = logging.getLogger(__name__)
            logger.debug(f"Direct dict instantiation failed, trying text format: {e}")

            # Convert dict to text format
            lines = []
            for key, value in data_dict.items():
                # Format value appropriately
                if isinstance(value, list):
                    value_str = " ".join(str(v) for v in value)
                else:
                    value_str = str(value)
                lines.append(f"{key} = {value_str}")

            text = "\n".join(lines)

            # Use hydrate to parse
            return ConfigModelFactory.hydrate(model_class, text)

    @staticmethod
    def _build_alias_map(model_class: type[BaseModel]) -> dict[str, str]:
        """
        Build alias map for AMReX dot notation to Python underscores.

        Maps parameter names (in both formats) to Pydantic field names:
        - 'amr.n_cell' → 'amr_n_cell' (for applying modifications)
        - 'amr_n_cell' → 'amr_n_cell' (for direct field access)

        Args:
            model_class: Pydantic model class (created by create_from_schema)

        Returns
        -------
            Dict mapping parameter names to field names

        Example:
            >>> alias_map = ConfigModelFactory._build_alias_map(ConfigModel)
            >>> alias_map['amr.n_cell']
            'amr_n_cell'
            >>> alias_map['amr_n_cell']
            'amr_n_cell'
        """
        alias_map = {}

        for field_name, field_info in model_class.model_fields.items():
            # 1. Map field name to itself (amr_n_cell → amr_n_cell)
            alias_map[field_name] = field_name

            # 2. Map alias to field name (amr.n_cell → amr_n_cell)
            if field_info.alias:
                alias_map[field_info.alias] = field_name

        return alias_map

    @staticmethod
    def _flatten_values(values: list[Any]) -> list[Any]:
        flattened: list[Any] = []
        for v in values:
            if isinstance(v, list):
                flattened.extend(v)
            else:
                flattened.append(v)
        return flattened

    @staticmethod
    def _looks_like_array_value(value: Any) -> bool:
        if isinstance(value, list):
            return len(value) > 1
        if isinstance(value, str):
            return len(value.split()) > 1
        return False

    @staticmethod
    def _merge_duplicate_param_values(
        param: str,
        values: list[Any],
        field_info,
        merge_strategy: str,
        force_append: bool = False,
    ) -> Any:
        if not ConfigModelFactory._is_array_parameter(field_info.annotation, field_info):
            return values[-1]

        if force_append or merge_strategy == "append":
            merged = ConfigModelFactory._flatten_values(values)
            logger.debug(
                f"[ConfigFactory] Appended {len(values)} values for array param {param}: {merged}"
            )
            return merged

        if len(values) > 1 and all(ConfigModelFactory._looks_like_array_value(v) for v in values):
            logger.warning(
                f"[ConfigFactory] Duplicate array values for {param} look like full arrays; "
                f"keeping last value"
            )

        return values[-1]

    @staticmethod
    def remap_failed_modifications(
            failed_mods: list[tuple[str, any]],
            config_model: BaseModel,
            config_service,
            solver_config: type = None,  # e.g., BaseAMReXConfig subclass
            return_mapping: bool = False,
            return_details: bool = False,
            remap_strategy: str = "last_write",
    ) -> list[tuple[str, any]]:
        """
        LLM pass to map semantic parameter names to schema fields.

        Parameters
        ----------
        failed_mods : list of tuple[str, Any]
            Semantic parameters that failed schema matching.
        config_model : BaseModel
            Pydantic model with schema fields.
        config_service : object
            ConfigService for API access.
        solver_config : type, optional
            Solver config class with format hints.
        return_mapping : bool, optional
            Include the mapping dict in the return value.
        return_details : bool, optional
            Include detailed remap diagnostics.
        remap_strategy : str, optional
            Strategy for handling duplicate parameters.

        Returns
        -------
        list or tuple
            Remapped (schema_alias, value) tuples and optional mapping/details.
        """
        if not failed_mods:
            return []

        # Build schema info with aliases (include descriptions when available)
        schema_fields = []
        for field_name, field_info in type(config_model).model_fields.items():
            alias = field_info.alias or field_name
            doc = field_info.description or ""
            doc_suffix = f" — {doc}" if doc else ""
            schema_fields.append(f"{alias} ({field_info.annotation}){doc_suffix}")

        # Get format hints from solver config
        format_hints = ""
        if solver_config and hasattr(solver_config, 'parameter_format_hints'):
            format_hints = "\n".join(
                f"- {k}: {v}" for k, v in solver_config.parameter_format_hints.items()
            )

        prompt_template = None
        if solver_config and hasattr(solver_config, "get_prompt_templates"):
            prompt_template = solver_config.get_prompt_templates().get(
                "remap", {}
            ).get("template")

        if not prompt_template:
            try:
                from database.configs.base_amrex_config import BaseAMReXConfig
                prompt_template = BaseAMReXConfig.get_prompt_templates().get(
                    "remap", {}
                ).get("template")
            except Exception:
                prompt_template = None

        if not prompt_template:
            prompt_template = """Map semantic parameter names to schema field aliases.

Failed parameters needing remapping:
{failed_list}

Available schema fields (alias + type):
{schema_list}

Format hints:
{format_hints}

For each failed parameter, find the closest matching schema field.
If a value needs reformatting (e.g., composition lists -> "SPECIES:value" format), provide formatted_value.

Return JSON: {{"mappings": [
  {{"from": "jet_diameter", "to": "prob.jet_rad", "transform": "divide_by_2", "formatted_value": null}},
  {{"from": "jet_composition", "to": "prob.jet_Y", "transform": null, "formatted_value": "H2:0.7 N2:0.18 He:0.12"}}
]}}

Supported transforms: null, "divide_by_2", "multiply_by_2", "to_meters", "to_kelvin"
If no match exists, set "to": null."""

        # Pre-normalize dimensional suffixes before LLM remap (e.g., foo_x/foo.y -> foo)
        alias_map = ConfigModelFactory._build_alias_map(type(config_model))
        alias_set = set(alias_map.keys())
        axis_suffix_re = re.compile(r"(?:[._])(x|y|z)$", re.IGNORECASE)
        axis_values: dict[str, dict[str, Any]] = {}
        base_values: dict[str, list[Any]] = {}
        normalization_map: dict[str, str] = {}
        normalized_failed_mods: list[tuple[str, Any]] = []
        for name, value in failed_mods:
            axis_match = axis_suffix_re.search(name)
            stripped = axis_suffix_re.sub("", name)
            if axis_match and stripped in alias_set and name not in alias_set:
                normalization_map[name] = stripped
                axis = axis_match.group(1).lower()
                axis_values.setdefault(stripped, {})[axis] = value
                normalized_failed_mods.append((stripped, value))
                continue
            if name not in alias_set and stripped in alias_set:
                normalization_map[name] = stripped
                normalized_failed_mods.append((stripped, value))
                base_values.setdefault(stripped, []).append(value)
                continue
            normalized_failed_mods.append((name, value))

        failed_list = "\n".join(f"- {name}: {value}" for name, value in normalized_failed_mods)
        schema_list = "\n".join(f"- {f}" for f in schema_fields[:150])

        try:
            from src.config import get_llm_client
            from src.utils.llm_calls import LLMCallSpec, call_llm

            client = get_llm_client(config_service)
            spec = LLMCallSpec(
                model=config_service.llm_model,
                response_model=MappingExtraction,
                messages=[{"role": "user", "content": prompt_template.format(
                    failed_list=failed_list,
                    schema_list=schema_list,
                    format_hints=format_hints or "None provided"
                )}],
                temperature=0.1,
                purpose="remap_failed_modifications",
                template_name="remap",
                template_source="solver_config",
            )
            result = call_llm(client, spec, config=config_service)

            logger.debug(f"[Remap] LLM response: {len(result.mappings)} mappings")

            transforms = {
                'divide_by_2': lambda v: v / 2 if isinstance(v, (int, float)) else v,
                'multiply_by_2': lambda v: v * 2 if isinstance(v, (int, float)) else v,
                'to_meters': lambda v: v / 1000 if isinstance(v, (int, float)) else v,
                'to_kelvin': lambda v: v + 273.15 if isinstance(v, (int, float)) else v,
            }

            failed_values: dict[str, list[Any]] = {}
            for name, value in normalized_failed_mods:
                failed_values.setdefault(name, []).append(value)

            remapped: list[tuple[str, Any]] = []
            remap_mapping: dict[str, str] = {}
            remap_details: list[RemapResult] = []
            needs_escalation = []
            force_append_params: set[str] = set()
            merge_strategy = remap_strategy or "last_write"

            for m in result.mappings:
                if not m.to or m.from_param not in failed_values:
                    continue
                remap_mapping[m.from_param] = m.to

                if m.transform == 'needs_context':
                    needs_escalation.append((m.from_param, failed_values[m.from_param]))
                    continue

                values = failed_values.get(m.from_param, [])
                # If axis values exist for this base param, order x->y->z
                if m.from_param in axis_values:
                    ordered = []
                    for axis in ("x", "y", "z"):
                        if axis in axis_values[m.from_param]:
                            ordered.append(axis_values[m.from_param][axis])
                    # Append any non-axis values seen for this param (if any)
                    extra = [v for v in values if v not in ordered]
                    values = ordered + extra
                    force_append_params.add(m.to)

                if m.formatted_value:
                    remapped.append((m.to, m.formatted_value))
                    remap_details.append({
                        "from_param": m.from_param,
                        "to_param": m.to,
                        "transform": m.transform,
                        "formatted_value": m.formatted_value,
                        "values": values,
                        "reason": "formatted_value",
                    })
                else:
                    for value in values:
                        if m.transform in transforms:
                            value = transforms[m.transform](value)
                        remapped.append((m.to, value))
                    remap_details.append({
                        "from_param": m.from_param,
                        "to_param": m.to,
                        "transform": m.transform,
                        "formatted_value": None,
                        "values": values,
                        "reason": "transform" if m.transform else None,
                    })

            if needs_escalation:
                logger.warning(f"[Remap] {len(needs_escalation)} params need context: {[n for n,v in needs_escalation]}")

            # Merge duplicate remaps for array parameters (e.g., amr.n_cell)
            if remapped:
                alias_map = ConfigModelFactory._build_alias_map(type(config_model))
                param_order: list[str] = []
                param_values: dict[str, list[Any]] = {}
                for param, value in remapped:
                    if param not in param_values:
                        param_order.append(param)
                        param_values[param] = []
                    param_values[param].append(value)

                merged_remapped: list[tuple[str, Any]] = []
                for param in param_order:
                    values = param_values[param]
                    field_name = alias_map.get(param)
                    if len(values) > 1 and field_name:
                        field_info = type(config_model).model_fields[field_name]
                        merged_value = ConfigModelFactory._merge_duplicate_param_values(
                            param,
                            values,
                            field_info,
                            merge_strategy,
                            force_append=(param in force_append_params),
                        )
                        merged_remapped.append((param, merged_value))
                        continue
                    merged_remapped.append((param, values[-1]))
                remapped = merged_remapped

            # Add normalization mappings for original unresolved params
            for original, normalized in normalization_map.items():
                remap_mapping[original] = remap_mapping.get(normalized, normalized)

            logger.debug(f"[Remap] Remapped {len(remapped)}/{len(normalized_failed_mods)} failed parameters")
            if return_mapping and return_details:
                return remapped, remap_mapping, remap_details
            if return_mapping:
                return remapped, remap_mapping
            if return_details:
                return remapped, remap_details
            return remapped

        except Exception as e:
            logger.warning(f"[Remap] Failed: {e}")
            if return_mapping and return_details:
                return [], {}, []
            if return_mapping:
                return [], {}
            if return_details:
                return [], []
            return []

    @staticmethod
    def _build_suggested_params(
        unresolved_params: list[tuple[str, Any]],
        alias_map: dict[str, str],
        remap_mapping: dict[str, str] | None = None,
    ) -> dict[str, Any]:
        available_by_prefix: dict[str, list[str]] = {}
        for alias in alias_map:
            prefix = alias.split('.')[0] if '.' in alias else alias.split('_')[0]
            available_by_prefix.setdefault(prefix, []).append(alias)

        suggested_params: dict[str, Any] = {}
        remap_mapping = remap_mapping or {}
        for param, _value in unresolved_params:
            if param in remap_mapping:
                suggested_params[param] = [remap_mapping[param]]
                continue
            keywords = param.lower().replace('_', ' ').replace('.', ' ').split()
            relevant: list[str] = []
            for prefix, params in available_by_prefix.items():
                if any(kw in prefix.lower() for kw in keywords):
                    relevant.extend(params[:10])
            suggested_params[param] = relevant[:20] if relevant else list(alias_map.keys())[:20]
        return suggested_params

    @staticmethod
    def _heuristic_remap(
        unresolved_params: list[tuple[str, Any]],
        alias_map: dict[str, str],
    ) -> dict[str, str]:
        """Heuristic remap for common grid/level/step terms."""
        mapping: dict[str, str] = {}
        alias_keys = set(alias_map.keys())
        for param, _value in unresolved_params:
            p = param.lower()
            if ("grid" in p or "ncell" in p or "n_cell" in p or "nx" in p or "ny" in p) and "amr.n_cell" in alias_keys:
                mapping[param] = "amr.n_cell"
                continue
            if ("level" in p or "amr_levels" in p) and "amr.max_level" in alias_keys:
                mapping[param] = "amr.max_level"
                continue
            if ("timestep" in p or "time_steps" in p or p.endswith(".nt") or p.endswith(".nstep")) and "amr.max_step" in alias_keys:
                mapping[param] = "amr.max_step"
                continue
        return mapping

    @classmethod
    def build_parameter_resolution_feedback(
        cls,
        unresolved_params: list[tuple[str, Any]],
        config_service: Any | None = None,
        solver_config: type | None = None,
        config_model: BaseModel | None = None,
        schema_path: Path | None = None,
        build_config: dict[str, str] | None = None,
        remap_mapping: dict[str, str] | None = None,
        available_schema_params: list[str] | None = None,
    ) -> dict[str, Any]:
        """
        Build guidance payload for unresolved parameter remapping.

        Parameters
        ----------
        unresolved_params : list of tuple[str, Any]
            Parameters that failed schema resolution.
        config_service : object or None, optional
            ConfigService for optional LLM remapping.
        solver_config : type or None, optional
            Solver config class with format hints.
        config_model : BaseModel or None, optional
            Existing config model for alias inspection.
        schema_path : Path or None, optional
            Schema path for building a model if needed.
        build_config : dict or None, optional
            Build flags to filter schema parameters.
        remap_mapping : dict or None, optional
            Known remap mapping for unresolved params.
        available_schema_params : list of str or None, optional
            Precomputed available schema parameters.

        Returns
        -------
        dict
            Resolution guidance payload with suggestions and mapping data.
        """
        if not unresolved_params:
            return {
                "unresolved_parameters": [],
                "available_schema_params": available_schema_params or [],
                "suggested_params": {},
                "remap_success_count": 0,
                "resolution_guidance": "No unresolved parameters."
            }

        if config_model is None:
            if not schema_path:
                return {
                    "unresolved_parameters": unresolved_params,
                    "available_schema_params": available_schema_params or [],
                    "suggested_params": {},
                    "remap_success_count": 0,
                    "resolution_guidance": (
                        f"{len(unresolved_params)} parameters could not be mapped "
                        f"to schema: {[p[0] for p in unresolved_params]}."
                    )
                }
            schema = cls.load_schema(schema_path)
            model_class = cls.create_from_schema(schema, build_config or {})
            config_model = model_class()

        alias_map = cls._build_alias_map(type(config_model))
        available = available_schema_params or list(alias_map.keys())

        remap_success_count = 0
        remap_mapping_local = remap_mapping or {}
        if not remap_mapping_local:
            remap_mapping_local = cls._heuristic_remap(unresolved_params, alias_map)
        if not remap_mapping and config_service:
            remapped, remap_mapping_local = cls.remap_failed_modifications(
                unresolved_params,
                config_model,
                config_service,
                solver_config,
                return_mapping=True,
                remap_strategy=getattr(config_service, "remap_strategy", "last_write")
            )
            remap_success_count = len(remapped)

        suggested_params = cls._build_suggested_params(
            unresolved_params,
            alias_map,
            remap_mapping_local
        )

        resolution_guidance = (
            f"{len(unresolved_params)} parameters could not be mapped to schema: "
            f"{[p[0] for p in unresolved_params]}. "
            f"Remap attempted: {remap_success_count} succeeded."
        )

        return {
            "unresolved_parameters": unresolved_params,
            "available_schema_params": available,
            "suggested_params": suggested_params,
            "remap_success_count": remap_success_count,
            "remap_mapping": remap_mapping_local,
            "resolution_guidance": resolution_guidance
        }

    @classmethod
    def apply_modifications(
        cls,
        config: BaseModel,
        modifications: dict[str, Any] | list[tuple[str, Any]],
        config_service: Any | None = None,
        baseline_params: dict[str, Any] | None = None,
        return_details: bool = False
    ) -> BaseModel | dict[str, Any]:
        """
        Apply modifications to a Pydantic config model.

        Parameters
        ----------
        config : BaseModel
            Hydrated Pydantic model instance.
        modifications : dict or list of tuple
            Parameter/value pairs or list of (parameter_name, value) tuples.
        config_service : object or None, optional
            Config service for LLM remap fallback.
        baseline_params : dict or None, optional
            Optional baseline parameters for remap context.
        return_details : bool, optional
            When True, return a dict with metadata and the config model.

        Returns
        -------
        BaseModel or dict
            Modified model or detailed result payload.
        """
        modifications_list = (
            list(modifications.items())
            if isinstance(modifications, dict)
            else list(modifications)
        )
        logger.debug("[DATA TRANSFER] apply_modifications called")
        logger.debug(f"[DATA TRANSFER]   - modifications count: {len(modifications_list)}")
        logger.debug(f"[DATA TRANSFER]   - config type: {type(config).__name__}")

        logger.debug(f"[ConfigFactory] Applying {len(modifications_list)} modifications")
        logger.debug(f"[ConfigFactory] Modifications: {modifications_list}")

        # Build alias → field name mapping using dedicated method
        unresolved_params = []  # Renamed from unknown_params
        alias_map = ConfigModelFactory._build_alias_map(type(config))
        logger.debug(f"[ConfigFactory] Built alias_map with {len(alias_map)} entries")
        logger.debug(f"[ConfigFactory] Sample mappings: {list(alias_map.items())[:5]}")

        # Normalize and merge duplicate params for array fields
        normalized_mods: list[tuple[str, Any]] = []
        for mod in modifications_list:
            # Handle different modification formats
            if isinstance(mod, dict):
                # Dict format from Architect: {"section": "amr", "parameter": "max_level", "value": "2"}
                section = mod.get("section", "")
                parameter = mod.get("parameter", "")
                value = mod.get("value")

                # Construct full parameter name
                param = f"{section}.{parameter}" if section else parameter
            elif isinstance(mod, (tuple, list)) and len(mod) == 2:
                # Tuple format: ("amr.max_level", "2")
                param, value = mod
            else:
                logger.warning(f"Unknown modification format: {mod}")
                continue
            normalized_mods.append((param, value))

        merged_mods: list[tuple[str, Any]] = []
        applied_params: list[str] = []
        merge_strategy = getattr(config_service, "remap_strategy", "last_write") if config_service else "last_write"
        if normalized_mods:
            param_order: list[str] = []
            param_values: dict[str, list[Any]] = {}
            for param, value in normalized_mods:
                if param not in param_values:
                    param_order.append(param)
                    param_values[param] = []
                param_values[param].append(value)

            for param in param_order:
                values = param_values[param]
                field_name = alias_map.get(param)
                if len(values) > 1 and field_name:
                    field_info = type(config).model_fields[field_name]
                    merged_value = ConfigModelFactory._merge_duplicate_param_values(
                        param,
                        values,
                        field_info,
                        merge_strategy,
                    )
                    merged_mods.append((param, merged_value))
                    applied_params.append(param)
                    continue
                # Non-array or unknown params: keep last value
                merged_mods.append((param, values[-1]))
                applied_params.append(param)
        else:
            merged_mods = []

        for param, value in merged_mods:

            # 1. Resolve alias to field name
            field_name = alias_map.get(param)
            logger.debug(f"Resolving '{param}' → field_name='{field_name}'")

            if field_name is None:
                logger.warning(f"Unresolved parameter '{param}' - not in model schema")
                logger.debug(f"Available aliases: {sorted(alias_map.keys())[:10]}")
                unresolved_params.append((param, value))

                # Try to set anyway if extra='allow'
                try:
                    # Convert dot notation to underscore for attribute name
                    attr_name = param.replace('.', '_')
                    setattr(config, attr_name, value)
                    logger.debug(f"Set extra field: {attr_name} = {value}")
                except Exception as e:
                    logger.warning(f"Could not set {param}: {e}")
                continue

            # 2. Get field info for type coercion
            field_info = type(config).model_fields[field_name]
            field_type = field_info.annotation

            # 3. Type coercion using AMReX-aware semantics
            coerced_value = ConfigModelFactory._coerce_amrex_value(
                value,
                field_type,
                field_info
            )

            # 4. Set the attribute
            try:
                old_value = getattr(config, field_name, None)
                setattr(config, field_name, coerced_value)
                logger.debug(
                    f"[ConfigFactory] Set {field_name}: {old_value} → {coerced_value} "
                    f"(type: {type(coerced_value).__name__})"
                )
            except Exception as e:
                logger.error(f"[ConfigFactory] Failed to set {field_name}: {e}")

        resolution_attempted = False
        remap_count = 0
        remap_mapping: dict[str, str] = {}
        remap_details: list[RemapResult] = []
        solver_config = baseline_params if hasattr(baseline_params, "parameter_format_hints") else None
        if unresolved_params and config_service:
            logger.debug(f"[ConfigFactory] Attempting remap for {len(unresolved_params)} unresolved params")
            resolution_attempted = True
            remapped, remap_mapping, remap_details = ConfigModelFactory.remap_failed_modifications(
                unresolved_params,
                config,
                config_service,
                solver_config,
                return_mapping=True,
                return_details=True,
                remap_strategy=merge_strategy,
            )
            remap_count = len(remapped)
            logger.debug(f"[Remap] Remapped {remap_count}/{len(unresolved_params)} failed parameters")

            # Remove successfully remapped from unresolved list
            # (remap_failed_modifications applies them directly to config)
            # For now, keep original list - remap success is tracked separately

        logger.debug("[ConfigFactory] Completed applying modifications")

        if not return_details:
            return config

        suggested_params = ConfigModelFactory._build_suggested_params(
            unresolved_params,
            alias_map,
            remap_mapping
        )
        #Note not returning a downselected parameters here, but the full schema list
        logger.debug("[DATA TRANSFER] Returning dict with:")
        logger.debug(f"[DATA TRANSFER]   - unresolved_parameters: {len(unresolved_params)}")
        logger.debug(f"[DATA TRANSFER]   - available_schema_params: {len(list(alias_map.keys()))}")
        logger.debug(f"[DATA TRANSFER]   - suggested_params: {len(suggested_params)} mappings")

        return {
            "config": config,
            "unresolved_parameters": unresolved_params,
            "available_schema_params": list(alias_map.keys()),
            "resolution_attempted": resolution_attempted,
            "remap_success_count": remap_count,
            "suggested_params": suggested_params,
            "remap_mapping": remap_mapping,
            "remap_details": remap_details,
            "applied_params": applied_params
        }

    @staticmethod
    def _coerce_amrex_value(
        value: Any,
        expected_type: type,
        field_info
    ) -> Any:
        """
        Coerce value respecting AMReX ParmParse API semantics.

        AMReX API patterns (from AMReX_ParmParse.H):
        - query(name, scalar)     → is_array=False, required=False
        - queryarr(name, array)   → is_array=True,  required=False
        - get(name, scalar)       → is_array=False, required=True
        - getarr(name, array)     → is_array=True,  required=True

        Schema metadata (from build_schema.py):
        - is_array: method in ['getarr', 'queryarr']
        - required: method in ['get', 'getarr']

        Coercion rules:
        - is_array=True:  "64 64 64" → [64, 64, 64]
        - is_array=False: "0.9" → 0.9 (scalar)
        - is_array=False but multi-value: "2 2 2" → 2 (take first)

        Args:
            value: Modification value (usually string from Architect)
            expected_type: Pydantic field type (e.g., Union[int, List[int]])
            field_info: Field metadata with description

        Returns
        -------
            Properly typed value for AMReX
        """
        from typing import get_args, get_origin
        import types

        logger = logging.getLogger(__name__)

        # Reject C++ expressions early
        if ConfigModelFactory._is_cpp_expression(value):
            logger.warning(f"Rejecting C++ expression: {value}")
            return None  # Return None instead of polluting model

        # Already correct type - pass through
        if not isinstance(value, str):
            return value

        # Determine if parameter expects array based on schema metadata
        is_array_param = ConfigModelFactory._is_array_parameter(expected_type, field_info)

        # Handle Union types (unwrap Optional)
        origin = get_origin(expected_type)
        if origin in (Union, types.UnionType):
            type_args = get_args(expected_type)
            concrete_types = [t for t in type_args if t is not type(None)]

            if is_array_param:
                # queryarr/getarr parameter - prefer list types
                for target_type in concrete_types:
                    if get_origin(target_type) is list:
                        result = ConfigModelFactory._parse_array_value(value, target_type)
                        logger.debug(f"Coerced '{value}' to array {result} (is_array=True)")
                        return result
                # No list type found, try parsing as array anyway
                result = ConfigModelFactory._parse_array_value(value, list[int])
                logger.debug(f"Coerced '{value}' to array {result} (is_array=True, inferred)")
                return result
            else:
                # query/get parameter - prefer scalar types
                for target_type in concrete_types:
                    if target_type in [int, float, bool, str]:
                        try:
                            result = ConfigModelFactory._parse_scalar_value(value, target_type)
                            logger.debug(
                                f"Coerced '{value}' to {type(result).__name__} {result} "
                                f"(is_array=False, type={target_type.__name__})"
                            )
                            return result
                        except (ValueError, TypeError):
                            continue
                # Fallback: return string
                logger.debug(f"Could not coerce '{value}' to scalar, returning as string")
                return value

        # Single type (not Union)
        if is_array_param:
            result = ConfigModelFactory._parse_array_value(value, expected_type)
            logger.debug(f"Coerced '{value}' to array {result} (is_array=True, single type)")
            return result
        else:
            result = ConfigModelFactory._parse_scalar_value(value, expected_type)
            logger.debug(
                f"Coerced '{value}' to {type(result).__name__} {result} "
                f"(is_array=False, single type)"
            )
            return result

    @staticmethod
    def _is_array_parameter(expected_type: type, field_info) -> bool:
        """
        Determine if parameter expects array based on AMReX API.

        Checks schema metadata stored in field description:
        - "Array: True" → queryarr/getarr
        - "Array: False" → query/get

        Also checks type annotations for List hints.
        """
        from typing import get_args, get_origin
        import types

        # Strategy 1: Check description for explicit is_array metadata
        description = field_info.description or ''
        if 'Array: True' in description:
            return True
        if 'Array: False' in description:
            return False

        # Strategy 2: Check if type includes List
        origin = get_origin(expected_type)
        if origin in (Union, types.UnionType):
            type_args = get_args(expected_type)
            for arg in type_args:
                if get_origin(arg) is list:
                    return True
        elif origin is list:
            return True

        # Default: not an array parameter
        return False

    @staticmethod
    def _parse_array_value(value: str, target_type: type) -> list:
        """
        Parse AMReX array value per queryarr/getarr semantics.

        Input formats:
        - "64 64 64"       → [64, 64, 64]
        - "0.1 0.2 0.3"    → [0.1, 0.2, 0.3]
        - "true false"     → [True, False]
        - "file1 file2"    → ["file1", "file2"]

        AMReX uses whitespace-separated values for arrays.
        Reference: AMReX_ParmParse.H lines 170-174
        """
        from typing import get_args, get_origin

        logger = logging.getLogger(__name__)

        # Get inner type from List[int], List[float], etc.
        origin = get_origin(target_type)
        if origin is list:
            args = get_args(target_type)
            inner_type = args[0] if args else str
        else:
            # Target type is not a list, infer from value
            inner_type = int  # Default assumption

        # Split by whitespace (AMReX standard)
        parts = value.split()

        # Convert each part to inner type
        try:
            if inner_type is int:
                return [int(float(p)) for p in parts]  # Handle "64.0" → 64
            elif inner_type is float:
                return [float(p) for p in parts]
            elif inner_type is bool:
                return [p.lower() in ('true', '1', 'yes', 'on', 't') for p in parts]
            else:
                return parts  # List[str]
        except (ValueError, TypeError) as e:
            logger.warning(f"Failed to parse array '{value}': {e}")
            return parts  # Return as strings

    @staticmethod
    def _parse_scalar_value(value: str, target_type: type) -> Any:
        """
        Parse AMReX scalar value per query/get semantics.

        Handles single values:
        - "0.9"   → 0.9
        - "128"   → 128
        - "true"  → True
        - "file"  → "file"

        If value contains multiple numbers (e.g., "2 2 2"), takes first.
        This handles edge cases where scalar params get array-like input.

        Reference: AMReX_ParmParse.H lines 174-178
        """
        logger = logging.getLogger(__name__)

        # Handle space-separated (take first value only for scalar params)
        parts = value.split()
        scalar_str = parts[0] if parts else value

        try:
            if target_type is int:
                return int(float(scalar_str))  # Handle "2.0" → 2
            elif target_type is float:
                return float(scalar_str)
            elif target_type is bool:
                return scalar_str.lower() in ('true', '1', 'yes', 'on', 't')
            else:
                return scalar_str  # Keep as string
        except (ValueError, TypeError) as e:
            logger.warning(f"Failed to parse scalar '{value}' as {target_type.__name__}: {e}")
            return scalar_str  # Return as string

    @staticmethod
    def _coerce_value(value: Any, field_type: type, field_name: str) -> Any:
        """
        Use _coerce_amrex_value instead (deprecated).

        Legacy coercion method kept for backward compatibility.
        Provides basic type coercion without AMReX metadata awareness.
        """
        import logging
        from typing import get_args, get_origin

        logger = logging.getLogger(__name__)

        # If value is already correct type, return as-is
        if not isinstance(value, str):
            return value

        # Get the origin type (List, Union, etc.)
        origin = get_origin(field_type)

        # Handle List types
        if origin is list:
            args = get_args(field_type)
            if args:
                item_type = args[0]
                try:
                    if item_type is int:
                        return [int(x) for x in value.split()]
                    elif item_type is float:
                        return [float(x) for x in value.split()]
                    else:
                        return value.split()
                except ValueError as e:
                    logger.warning(f"Could not parse '{value}' as list: {e}")
                    return value
            return value.split()

        # Handle scalar types
        if field_type is int:
            try:
                return int(float(value))  # Handle "2.0" → 2
            except (ValueError, TypeError):
                pass
        elif field_type is float:
            try:
                return float(value)
            except (ValueError, TypeError):
                pass
        elif field_type is bool:
            if value.lower() in ['true', 'yes', '1', 't']:
                return True
            elif value.lower() in ['false', 'no', '0', 'f']:
                return False

        # Return as-is if no coercion needed or possible
        return value

    @staticmethod
    def serialize(
        config: BaseModel,
        preserve_comments: bool = False,
        original_text: str | None = None
    ) -> str:
        """
        Serialize Pydantic model back to AMReX inputs format.

        Per PRD Amendment C: Object Manipulation (typed storage)
        Handles Union types and flexible formats:
        - Union[int, List[int]]: Scalar "32" or array "32 64 96"
        - Union[float, List[float]]: Scalar "1.0" or array "1.0 2.0 3.0"
        - Union[str, List[str]]: Scalar or space-separated list

        Parameters
        ----------
        config : BaseModel
            Hydrated Pydantic model instance.
        preserve_comments : bool, optional
            If True, preserve original comments (Amendment C).
        original_text : str or None, optional
            Original inputs text for comment extraction.

        Returns
        -------
        str
            AMReX inputs text format.

        Note: Full comment preservation requires parsing original text.
              For now, returns clean key = value format.
        """
        # Get dict with original aliases (amr_n_cell → amr.n_cell)
        data = config.model_dump(by_alias=True, exclude_none=True)

        lines = []
        for key, value in sorted(data.items()):
            # Format value based on type
            # Handles Union types naturally:
            # - Lists → space-separated strings
            # - Scalars → string representation
            # - Bools → AMReX format (TRUE/FALSE)
            if isinstance(value, (list, tuple)):
                # Union[X, List[X]] with list value → space-separated
                value_str = " ".join(str(v) for v in value)
            elif isinstance(value, bool):
                # Union types that include bool → AMReX format
                value_str = "TRUE" if value else "FALSE"
            else:
                # Scalar values (Union[X, List[X]] with scalar, Union[float, str], etc.)
                value_str = str(value)

            # TODO: Preserve comments if original_text provided
            lines.append(f"{key} = {value_str}")

        return "\n".join(lines) + "\n"

    @staticmethod
    def _check_dependencies(
        dependencies: list[str],
        build_config: dict[str, str]
    ) -> bool:
        """
        Check if all dependencies are satisfied in build config.

        Supports complex expressions:
        - Simple flags: "USE_EB" → checks if TRUE
        - Equality: "DIM==3" → checks if DIM=3
        - Negation: "!USE_PARTICLES" → checks if FALSE
        - Greater than: "DIM>2" → checks if DIM>2
        """
        if not dependencies:
            return True

        for dep in dependencies:
            # Negation
            if dep.startswith('!'):
                flag = dep[1:]
                if build_config.get(flag, 'FALSE').upper() == 'TRUE':
                    return False

            # Equality
            elif '==' in dep:
                var, val = dep.split('==')
                if build_config.get(var.strip()) != val.strip():
                    return False

            # Greater than
            elif '>' in dep:
                var, val = dep.split('>')
                try:
                    if not (int(build_config.get(var.strip(), '0')) > int(val.strip())):
                        return False
                except ValueError:
                    return False

            # Simple flag check
            else:
                if build_config.get(dep, 'FALSE').upper() not in ['TRUE', 'ON', '1', 'YES']:
                    return False

        return True

    @staticmethod
    def _map_type(cpp_type: str, is_array: bool = False) -> type:
        """
        Map C++ type names to Python types with strict enforcement of coerced types.

        Per PRD Amendment C/D:
        - Object Manipulation: Store as typed Python objects (lists, floats, etc.)
        - Enable UQ sweeps: Allow float storage for numerical parameters
        - Strict typing: Enforce coerced values via Pydantic validation

        CRITICAL CHANGE: Removed str from numeric Union types to force proper coercion.
        Our _coerce_amrex_value() handles all string→type conversions, so we don't need
        str as an escape hatch. Pydantic will reject non-coerced strings, catching bugs.

        Handles AMReX schema type names:
          • IntVect → Union[int, List[int]] (coercion required)
          • RealVect → Union[float, List[float]] (coercion required)
          • int → Union[int, List[int]] (coercion required)
          • real → Union[float, None] (NO str fallback - use coercion!)
          • string → Union[str, List[str]] (only strings keep str)

        Args:
            cpp_type: Type name from schema (e.g., "IntVect", "real")
            is_array: Whether this is an array field

        Returns
        -------
            Python type (Union for array flexibility, strict for scalars)
        """
        # Handle None type (parameters without type information)
        if cpp_type is None:
            # For truly unknown types, allow strings but still prefer coercion
            return (str | list[str] | None) if is_array else (str | None)

        # Normalize type name (case-insensitive)
        type_lower = cpp_type.lower()

        # Handle Vector<T> and Array<T> template types - STRICT (no str)
        if 'vector<' in type_lower or 'array<' in type_lower:
            if 'real' in type_lower or 'float' in type_lower or 'double' in type_lower:
                # Vector<Real> → Union[float, List[float]] (NO str escape)
                return float | list[float]
            elif 'int' in type_lower:
                # Vector<int> → Union[int, List[int]] (NO str escape)
                return int | list[int]
            else:
                # Vector<string> → Union[str, List[str]] (strings OK for string vectors)
                return str | list[str]

        # AMReX vector types - STRICT (no str)
        if type_lower == 'intvect':
            # IntVect: scalar "64" or array "64 64 64"
            # Must be coerced to int or List[int] by _coerce_amrex_value
            return int | list[int]
        elif type_lower == 'realvect':
            # RealVect: scalar "0.5" or array "0.5 0.5 0.5"
            # Must be coerced to float or List[float] by _coerce_amrex_value
            return float | list[float]

        # Standard type mapping
        type_mapping = {
            "int": int,
            "long": int,
            "real": float,
            "double": float,
            "float": float,
            "bool": bool,
            "string": str,
        }

        base_type = type_mapping.get(type_lower, str)

        # Handle arrays with strict types (allow scalar OR array, but NOT strings for numeric)
        if is_array:
            # is_array=True means field can be an array OR scalar
            if base_type is int:
                # Coercion handles "8" → 8 or "8 8 8" → [8, 8, 8]
                return int | list[int]
            elif base_type is float:
                # Coercion handles "0.9" → 0.9 or "0.1 0.2" → [0.1, 0.2]
                return float | list[float]
            elif base_type is str:
                # String arrays: keep str and List[str]
                return str | list[str]
            elif base_type is bool:
                # Boolean arrays: strict (no str fallback)
                return bool | list[bool]
            else:
                return base_type | list[base_type]

        # Scalar types: STRICT (no str fallback for numeric types)
        # Coercion happens in hydrate() and apply_modifications()
        if base_type is float:
            # Floats: STRICT - "0.9" must be coerced to 0.9
            # No Union[float, str] escape hatch!
            return float
        elif base_type is int:
            # Ints: STRICT - "128" must be coerced to 128
            # No Union[int, str] escape hatch!
            return int
        elif base_type is bool:
            # Bools: STRICT - "true" must be coerced to True
            return bool
        elif base_type is str:
            # Strings: Allow str (they don't need coercion)
            return str

        # Fallback for truly unknown types
        return str
    @classmethod
    def resolve_schema_path(
        cls,
        solver_config,
        schema_dir: Path,
        repo_path: Path
    ) -> Path:
        """
        Dynamically resolve schema path using configured strategy.

        Strategies:
          • newest: Most recently modified schema (default)
          • exact: Match git hash, rebuild if missing (Digital Twin)
          • tag: Specific version tag (reproducibility)

        Parameters
        ----------
        solver_config : object
            Solver configuration object (has code_name, schema_strategy).
        schema_dir : Path
            Directory containing generated schemas.
        repo_path : Path
            Path to solver source repository.

        Returns
        -------
        Path
            Resolved schema file path.

        Raises
        ------
        FileNotFoundError
            If schema could not be resolved.
        """
        solver_name_orig = solver_config.code_name  # Preserve for error messages
        solver_name = solver_name_orig.lower()  # Normalize for file matching
        strategy = getattr(solver_config, 'schema_strategy', 'newest')

        def _load_schema_metadata(schema_path: Path) -> dict[str, Any]:
            try:
                with open(schema_path) as f:
                    data = json.load(f)
                if isinstance(data, dict):
                    return data.get("metadata", {})
            except Exception as exc:
                logger.debug("Failed to read schema metadata from %s: %s", schema_path, exc)
            return {}

        def _commit_matches(expected: str, actual: str) -> bool:
            if not expected or not actual:
                return False
            return expected.startswith(actual) or actual.startswith(expected)

        def _get_dependency_commits() -> dict[str, str]:
            from database.scripts.dependency_discovery import DependencyDiscovery
            import subprocess

            commits: dict[str, str] = {}
            deps = DependencyDiscovery.discover(repo_path)
            for dep in deps:
                if dep.commit:
                    commits[dep.name.lower()] = dep.commit

            try:
                result = subprocess.run(
                    ['git', 'rev-parse', 'HEAD'],
                    cwd=repo_path,
                    capture_output=True,
                    text=True,
                    check=True,
                    timeout=5
                )
                commits[repo_path.name.lower()] = result.stdout.strip()
            except Exception:
                commits[repo_path.name.lower()] = "unknown"

            return commits

        # STRATEGY: EXACT (Digital Twin - match git hash)
        if strategy == 'exact':
            pattern = getattr(solver_config, "schema_pattern", None)
            if not isinstance(pattern, str) or not pattern:
                pattern = f"{solver_name}_schema_*.json"
            matches = list(schema_dir.glob(pattern))
            if not matches:
                matches = []

            expected_hash = cls._get_git_hash(repo_path)
            if expected_hash:
                for candidate in matches:
                    if expected_hash in candidate.name:
                        logger.debug(
                            "Found exact schema match via filename hash: %s",
                            candidate.name
                        )
                        return candidate

            expected_commits = _get_dependency_commits()
            expected_version = getattr(solver_config, "schema_version", None)
            for candidate in matches:
                metadata = _load_schema_metadata(candidate)
                repo_commits = metadata.get("repo_commits", {})
                schema_version = metadata.get("schema_version")
                if expected_version is not None and schema_version != expected_version:
                    continue
                if not repo_commits:
                    continue

                all_match = True
                for name, commit in expected_commits.items():
                    if name not in repo_commits or not _commit_matches(commit, repo_commits.get(name, "")):
                        all_match = False
                        break
                if all_match:
                    logger.debug("Found exact schema match via metadata: %s", candidate.name)
                    return candidate

            logger.warning("No exact schema metadata match found; rebuilding schema.")
            from database.scripts.build_schema import SchemaBuilder
            from database.configs.base_amrex_config import BaseAMReXConfig

            source_dirs = getattr(
                solver_config,
                "schema_source_patterns",
                BaseAMReXConfig.schema_source_patterns
            )
            if not isinstance(source_dirs, (list, tuple)):
                source_dirs = BaseAMReXConfig.schema_source_patterns
            builder = SchemaBuilder(repo_path)
            build_requirements = getattr(solver_config, "build_requirements", None)
            scan_config = solver_config if isinstance(build_requirements, (list, tuple, dict)) else None
            builder.scan_source_code(source_dirs, solver_config=scan_config)
            new_schema_path = builder.save(schema_dir, solver_name=solver_name)
            logger.debug("Built schema: %s", new_schema_path.name)
            return new_schema_path

        # STRATEGY: TAG (Reproducibility - specific version)
        elif strategy == 'tag':
            tag = getattr(solver_config, 'schema_tag', 'latest')
            target_file = schema_dir / f"{solver_name}_schema_{tag}.json"

            if target_file.exists():
                logger.debug(f"Found tagged schema: {tag}")
                return target_file

            raise FileNotFoundError(
                f"Schema tag '{tag}' not found for {solver_name}. "
                f"Available: {list(schema_dir.glob(f'{solver_name}_schema_*.json'))}"
            )

        # STRATEGY: NEWEST (Default - most recent)
        else:  # strategy == 'newest' or fallback
            pattern = getattr(solver_config, "schema_pattern", None)
            if not isinstance(pattern, str) or not pattern:
                pattern = f"{solver_name}_schema_*.json"
            matches = list(schema_dir.glob(pattern))

            if not matches:
                raise FileNotFoundError(
                    f"No schema found for solver '{solver_name_orig}' "
                    f"in {schema_dir}. Expected pattern: {pattern}. "
                    f"Run 'python database/scripts/build_schema.py' first."
                )

            # Return most recently modified
            latest = max(matches, key=lambda p: p.stat().st_mtime)
            logger.debug(f"Using newest schema: {latest.name}")
            return latest

    @staticmethod
    def _get_git_hash(repo_path: Path) -> str:
        """
        Get short git commit hash from repository.

        Args:
            repo_path: Path to git repository

        Returns
        -------
            Short commit hash (7 chars) or "unknown"
        """
        import subprocess

        try:
            result = subprocess.run(
                ['git', 'rev-parse', '--short', 'HEAD'],
                cwd=repo_path,
                capture_output=True,
                text=True,
                check=True,
                timeout=5
            )
            return result.stdout.strip()
        except Exception as e:
            logger.warning(f"Could not get git hash from {repo_path}: {e}")
            return "unknown"

    @staticmethod
    def _convert_value(value: Any, target_type: type) -> Any:
        """Convert string default to target type."""
        if value is None:
            return None

        if target_type is int:
            return int(value)
        elif target_type is float:
            return float(value)
        elif target_type is bool:
            if isinstance(value, bool):
                return value
            return str(value).upper() in ("TRUE", "ON", "1", "YES")
        else:
            return str(value)
